### ISSUE TITLE
Update Roadmap with [Spark/Meridian] milestones

### ISSUE THREAD

**Issue by MF416** [filecoin-station/zinnia#343]
- [ ] Spark path to lab week
- [ ] Spark longer-term path to decentralization
- [ ] Spark Presentation / deliverable for FilDev
- [ ] Meridian Presentation / deliverable for FilDev
