### ISSUE TITLE
Hello world from JavaScript

### ISSUE THREAD

**Issue by bajtos** [filecoin-station/zinnia#5]
The first step towards Zinnia runtime for JavaScript modules.

## Demo

Run a JavaScript module that prints "Hello world"

## Discussion points

- What API to use for logging? As a JS author, I would love `console.log` and friends.
- Can we hide Deno APIs (maybe delete them from the global object?) from the modules?
- What is the DX for "change code" - "run code"? Maybe `zinnia run my-module.js`?
- How are we going to test this functionality? It would be great to setup a CI pipeline for Zinnia.
- Bare-bone documentation for JS module authors to make it easy to add more content while adding new features.

## Tasks

- [x] `zinnia` CLI + argument parsing
- [x] runtime based on `deno_core`
- [x] hide Deno-related APIs
- [x] expose `console` APIs (see https://developer.mozilla.org/en-US/docs/Web/API/console)
- [x] tests
- [x] CI pipeline - build (reject compiler warnings!), lint, test
- [x] documentation for JS module authors
