### ISSUE TITLE
Integration with Filecoin Station

### ISSUE THREAD

**Issue by bajtos** [filecoin-station/zinnia#75]
StarMaps entry: https://github.com/filecoin-station/roadmap/issues/8

Once the first module is built on Zinnia, we should quickly integrate Zinnia into the Station. 

For example, as a short-term solution, we can use the current approach where each module is a standalone executable binary, with the slight modification that new modules will contain two pieces - Zinnia CLI and the module JS bundle.

On the Zinnia side, we may need to implement platform APIs for the following features:

- Get the FIL wallet address for receiving rewards.
- Publish Activity Log items.
- Report completion of jobs.

**Tasks**

- [x] Architecture decision record: 
   #121
- [x] Zinnia API for the wallet address, including docs for module builders: 
   #123 
- [x] Zinnia API for publishing activity logs, including docs for module builders.
   #124
- [x] Explain when to use `Zinnia.log.info` and when to use Console APIs like `console.log` 
   #124
  - see https://github.com/filecoin-station/zinnia/pull/121#discussion_r1143289663
- [x] Zinnia API for reporting job completion, including docs for module builders: 
   #124
- [x] Binary to be used by Station
  #141 
- [x] Configuration via env vars (wallet address, state root dir)
  #141
- [x] CD pipeline to build `zinniad` release artefacts
  #158 
  #159
- [x] A new Zinnia module that will be run by `zinniad` & the Station
  https://github.com/filecoin-station/mod-peer-checker/pull/1
- [x] Integration into Station Core, including automation to update Zinnia & modules.
  https://github.com/filecoin-station/core/pull/92
  https://github.com/filecoin-station/zinnia/pull/172
- ~~Integration into Station Desktop, including automation to update Zinnia & modules.~~ 
  → moved to https://github.com/filecoin-station/roadmap/issues/15
- ~~Documentation for module builders explaining how to add their new module to Station~~
  → we are not ready for adding 3rd-party Zinnia modules yet
- [ ] Documentation for `zinniad` (add a README)
  → https://github.com/filecoin-station/zinnia/pull/203
